# Generated by Django 4.1.7 on 2023-10-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PressRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media_name", models.CharField(max_length=255)),
                ("header", models.CharField(max_length=255)),
                ("link", models.URLField()),
                ("date", models.DateField()),
            ],
        ),
    ]
