# Generated by Django 4.1.7 on 2023-12-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pressrelease",
            name="link",
            field=models.URLField(max_length=300),
        ),
    ]
