# Generated by Django 4.1.7 on 2023-10-03 21:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image_url", models.CharField(max_length=200)),
                ("description", ckeditor.fields.RichTextField()),
            ],
        ),
    ]
