# Generated by Django 4.1.7 on 2023-10-10 21:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header", models.CharField(max_length=255)),
                ("text", ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("bi-wallet2", "Wallet"),
                            ("bi-paypal", "Paypal"),
                            ("bi-heart", "GoFundMe"),
                            ("bi-currency-bitcoin", "Bitcoin"),
                            ("bi-currency-ethereum", "ETH"),
                            ("bi-cash", "USDT (TRC20)"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SocialNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("bi-facebook", "Facebook"),
                            ("bi-twitter", "Twitter"),
                            ("bi-telegram", "Telegram"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("link", models.URLField()),
            ],
        ),
    ]
