# Generated by Django 4.1.7 on 2023-10-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0003_remove_webhero_button_remove_webhero_mission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
