# Generated by Django 4.1.7 on 2023-11-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0006_partner_name_alter_partner_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="description",
        ),
        migrations.RemoveField(
            model_name="card",
            name="title",
        ),
        migrations.RemoveField(
            model_name="mission",
            name="header",
        ),
        migrations.RemoveField(
            model_name="mission",
            name="text",
        ),
        migrations.AddField(
            model_name="card",
            name="description_text_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="title_text_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="mission",
            name="header_text_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="mission",
            name="text_text_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="TranslatedText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_id", models.CharField(max_length=100, unique=True)),
                ("language", models.CharField(max_length=10)),
                ("text", models.TextField()),
            ],
            options={
                "unique_together": {("text_id", "language")},
            },
        ),
    ]
