# Generated by Django 4.1.7 on 2023-11-24 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0007_remove_card_description_remove_card_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="description_text_id",
        ),
        migrations.RemoveField(
            model_name="card",
            name="title_text_id",
        ),
        migrations.RemoveField(
            model_name="mission",
            name="header_text_id",
        ),
        migrations.RemoveField(
            model_name="mission",
            name="text_text_id",
        ),
        migrations.AddField(
            model_name="card",
            name="description",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="card_description",
                to="main_page.translatedtext",
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="card_title",
                to="main_page.translatedtext",
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="header",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mission_header",
                to="main_page.translatedtext",
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="text",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mission_text",
                to="main_page.translatedtext",
            ),
        ),
        migrations.AlterField(
            model_name="translatedtext",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("ru", "Russian"),
                    ("uk", "Ukrainian"),
                    ("pl", "Polish"),
                ],
                default="ru",
                max_length=10,
            ),
        ),
    ]
