# Generated by Django 4.1.7 on 2023-11-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "main_page",
            "0009_crypto_alter_webhero_options_remove_webhero_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="image",
            field=models.URLField(
                blank=True, default="https://via.placeholder.com/150x50", null=True
            ),
        ),
    ]
