# Generated by Django 4.1.7 on 2023-12-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0010_alter_paymentmethod_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="link",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
