# Generated by Django 4.1.7 on 2023-12-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0011_alter_paymentmethod_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="image",
            field=models.CharField(
                blank=True,
                default="https://via.placeholder.com/150x50",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
