# Generated by Django 4.1.7 on 2023-12-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0012_alter_paymentmethod_image_alter_paymentmethod_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="webhero",
            options={},
        ),
        migrations.AddField(
            model_name="webhero",
            name="cars_count_label",
            field=models.CharField(
                blank=True, default="Автомобилей", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="cars_count_label_de",
            field=models.CharField(
                blank=True, default="Автомобилей", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="cars_count_label_en",
            field=models.CharField(
                blank=True, default="Автомобилей", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="cars_count_label_pl",
            field=models.CharField(
                blank=True, default="Автомобилей", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="cars_count_label_ru",
            field=models.CharField(
                blank=True, default="Автомобилей", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="cars_count_label_ua",
            field=models.CharField(
                blank=True, default="Автомобилей", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="days_of_rfu_label",
            field=models.CharField(
                blank=True, default="Дней RFU", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="days_of_rfu_label_de",
            field=models.CharField(
                blank=True, default="Дней RFU", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="days_of_rfu_label_en",
            field=models.CharField(
                blank=True, default="Дней RFU", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="days_of_rfu_label_pl",
            field=models.CharField(
                blank=True, default="Дней RFU", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="days_of_rfu_label_ru",
            field=models.CharField(
                blank=True, default="Дней RFU", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="days_of_rfu_label_ua",
            field=models.CharField(
                blank=True, default="Дней RFU", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="days_of_war_label",
            field=models.CharField(
                blank=True, default="Дней войны", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="days_of_war_label_de",
            field=models.CharField(
                blank=True, default="Дней войны", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="days_of_war_label_en",
            field=models.CharField(
                blank=True, default="Дней войны", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="days_of_war_label_pl",
            field=models.CharField(
                blank=True, default="Дней войны", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="days_of_war_label_ru",
            field=models.CharField(
                blank=True, default="Дней войны", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="days_of_war_label_ua",
            field=models.CharField(
                blank=True, default="Дней войны", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="flights_count_label",
            field=models.CharField(
                blank=True, default="Рейсов", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="flights_count_label_de",
            field=models.CharField(
                blank=True, default="Рейсов", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="flights_count_label_en",
            field=models.CharField(
                blank=True, default="Рейсов", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="flights_count_label_pl",
            field=models.CharField(
                blank=True, default="Рейсов", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="flights_count_label_ru",
            field=models.CharField(
                blank=True, default="Рейсов", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="flights_count_label_ua",
            field=models.CharField(
                blank=True, default="Рейсов", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="humanitarian_goods_weight_label",
            field=models.CharField(
                blank=True, default="тонн грузов", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="humanitarian_goods_weight_label_de",
            field=models.CharField(
                blank=True, default="тонн грузов", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="humanitarian_goods_weight_label_en",
            field=models.CharField(
                blank=True, default="тонн грузов", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="humanitarian_goods_weight_label_pl",
            field=models.CharField(
                blank=True, default="тонн грузов", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="humanitarian_goods_weight_label_ru",
            field=models.CharField(
                blank=True, default="тонн грузов", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="humanitarian_goods_weight_label_ua",
            field=models.CharField(
                blank=True, default="тонн грузов", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="shelter_refugees_count_label",
            field=models.CharField(
                blank=True, default="Беженцев в шелтере>", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="shelter_refugees_count_label_de",
            field=models.CharField(
                blank=True, default="Беженцев в шелтере>", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="shelter_refugees_count_label_en",
            field=models.CharField(
                blank=True, default="Беженцев в шелтере>", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="shelter_refugees_count_label_pl",
            field=models.CharField(
                blank=True, default="Беженцев в шелтере>", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="shelter_refugees_count_label_ru",
            field=models.CharField(
                blank=True, default="Беженцев в шелтере>", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="shelter_refugees_count_label_ua",
            field=models.CharField(
                blank=True, default="Беженцев в шелтере>", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="volunteers_count_label",
            field=models.CharField(
                blank=True, default="Волонтеров", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="volunteers_count_label_de",
            field=models.CharField(
                blank=True, default="Волонтеров", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="volunteers_count_label_en",
            field=models.CharField(
                blank=True, default="Волонтеров", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="volunteers_count_label_pl",
            field=models.CharField(
                blank=True, default="Волонтеров", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="volunteers_count_label_ru",
            field=models.CharField(
                blank=True, default="Волонтеров", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="webhero",
            name="volunteers_count_label_ua",
            field=models.CharField(
                blank=True, default="Волонтеров", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="webhero",
            name="cars_count",
            field=models.CharField(blank=True, default=350, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="webhero",
            name="days_of_rfu",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="webhero",
            name="days_of_war",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="webhero",
            name="flights_count",
            field=models.IntegerField(blank=True, default=92, null=True),
        ),
        migrations.AlterField(
            model_name="webhero",
            name="humanitarian_goods_weight",
            field=models.CharField(blank=True, default=50, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="webhero",
            name="shelter_refugees_count",
            field=models.CharField(
                blank=True, default="2600", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="webhero",
            name="volunteers_count",
            field=models.IntegerField(blank=True, default=320, null=True),
        ),
    ]
