# Generated by Django 4.1.7 on 2023-12-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0016_alter_webhero_cars_count_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhero",
            name="cars_count_label",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="webhero",
            name="cars_count_label_de",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="webhero",
            name="cars_count_label_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="webhero",
            name="cars_count_label_pl",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="webhero",
            name="cars_count_label_ru",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="webhero",
            name="cars_count_label_ua",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="webhero",
            name="h1_title",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="webhero",
            name="h1_title_de",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="webhero",
            name="h1_title_en",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="webhero",
            name="h1_title_pl",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="webhero",
            name="h1_title_ru",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="webhero",
            name="h1_title_ua",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
