# Generated by Django 4.1.7 on 2023-12-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0017_alter_webhero_cars_count_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhero",
            name="image_pattern1",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pattern1.png", "Pattern 1"),
                    ("pattern2.png", "Pattern 2"),
                    ("pattern3.png", "Pattern 3"),
                    ("pattern4.png", "Pattern 4"),
                    ("pattern5.png", "Pattern 5"),
                    ("pattern6.png", "Pattern 6"),
                    ("pattern7.png", "Pattern 7"),
                    ("pattern8.png", "Pattern 8"),
                    ("pattern9.png", "Pattern 9"),
                ],
                default="pattern1.png",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="webhero",
            name="image_pattern2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pattern1.png", "Pattern 1"),
                    ("pattern2.png", "Pattern 2"),
                    ("pattern3.png", "Pattern 3"),
                    ("pattern4.png", "Pattern 4"),
                    ("pattern5.png", "Pattern 5"),
                    ("pattern6.png", "Pattern 6"),
                    ("pattern7.png", "Pattern 7"),
                    ("pattern8.png", "Pattern 8"),
                    ("pattern9.png", "Pattern 9"),
                ],
                default="pattern1.png",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="webhero",
            name="image_pattern3",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pattern1.png", "Pattern 1"),
                    ("pattern2.png", "Pattern 2"),
                    ("pattern3.png", "Pattern 3"),
                    ("pattern4.png", "Pattern 4"),
                    ("pattern5.png", "Pattern 5"),
                    ("pattern6.png", "Pattern 6"),
                    ("pattern7.png", "Pattern 7"),
                    ("pattern8.png", "Pattern 8"),
                    ("pattern9.png", "Pattern 9"),
                ],
                default="pattern1.png",
                max_length=50,
            ),
        ),
    ]
