# Generated by Django 4.1.7 on 2023-12-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0018_alter_webhero_image_pattern1_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Partner",
        ),
        migrations.RemoveField(
            model_name="card",
            name="button",
        ),
        migrations.RemoveField(
            model_name="card",
            name="description",
        ),
        migrations.RemoveField(
            model_name="mission",
            name="header",
        ),
        migrations.AddField(
            model_name="card",
            name="text",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="mission",
            name="image",
            field=models.ImageField(
                default="https://via.placeholder.com/400", upload_to="cards/"
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="text_de",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="mission",
            name="text_en",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="mission",
            name="text_pl",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="mission",
            name="text_ru",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="mission",
            name="text_ua",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="mission",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="mission",
            name="title_de",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="mission",
            name="title_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="mission",
            name="title_pl",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="mission",
            name="title_ru",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="mission",
            name="title_ua",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="mission",
            name="text",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name="TranslatedText",
        ),
    ]
