# Generated by Django 4.1.7 on 2023-12-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0019_delete_partner_remove_card_button_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="image",
            field=models.ImageField(
                default="https://via.placeholder.com/400",
                upload_to="main_page/mission/",
            ),
        ),
    ]
