# Generated by Django 4.1.7 on 2023-12-17 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0020_alter_mission_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Card",
            new_name="OurWork",
        ),
    ]
