# Generated by Django 4.1.7 on 2023-12-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0021_rename_card_ourwork"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ourwork",
            name="image",
            field=models.ImageField(
                default="https://via.placeholder.com/400",
                upload_to="main_page/our_work/",
            ),
        ),
    ]
