# Generated by Django 4.1.7 on 2023-12-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0022_alter_ourwork_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="ourwork",
            name="text_de",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="ourwork",
            name="text_en",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="ourwork",
            name="text_pl",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="ourwork",
            name="text_ru",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="ourwork",
            name="text_ua",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="ourwork",
            name="title_de",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ourwork",
            name="title_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ourwork",
            name="title_pl",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ourwork",
            name="title_ru",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ourwork",
            name="title_ua",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
