# Generated by Django 4.1.7 on 2023-12-17 18:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0024_helpus"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModalWindow",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("text", ckeditor.fields.RichTextField()),
                ("text_en", ckeditor.fields.RichTextField(null=True)),
                ("text_ru", ckeditor.fields.RichTextField(null=True)),
                ("text_ua", ckeditor.fields.RichTextField(null=True)),
                ("text_pl", ckeditor.fields.RichTextField(null=True)),
                ("text_de", ckeditor.fields.RichTextField(null=True)),
                (
                    "image",
                    models.ImageField(
                        default="https://via.placeholder.com/400",
                        upload_to="main_page/modal_window/",
                    ),
                ),
            ],
        ),
    ]
