# Generated by Django 4.1.7 on 2023-12-17 22:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0028_cookiesconsent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cookiesconsent",
            name="analytics_text",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="cookiesconsent",
            name="analytics_text_de",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="cookiesconsent",
            name="analytics_text_en",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="cookiesconsent",
            name="analytics_text_pl",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="cookiesconsent",
            name="analytics_text_ru",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="cookiesconsent",
            name="analytics_text_ua",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="cookiesconsent",
            name="essential_text",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="cookiesconsent",
            name="essential_text_de",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="cookiesconsent",
            name="essential_text_en",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="cookiesconsent",
            name="essential_text_pl",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="cookiesconsent",
            name="essential_text_ru",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="cookiesconsent",
            name="essential_text_ua",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="cookiesconsent",
            name="functional_text",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="cookiesconsent",
            name="functional_text_de",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="cookiesconsent",
            name="functional_text_en",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="cookiesconsent",
            name="functional_text_pl",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="cookiesconsent",
            name="functional_text_ru",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="cookiesconsent",
            name="functional_text_ua",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="cookiesconsent",
            name="marketing_text",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="cookiesconsent",
            name="marketing_text_de",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="cookiesconsent",
            name="marketing_text_en",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="cookiesconsent",
            name="marketing_text_pl",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="cookiesconsent",
            name="marketing_text_ru",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="cookiesconsent",
            name="marketing_text_ua",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="cookiesconsent",
            name="performance_text",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="cookiesconsent",
            name="text",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="cookiesconsent",
            name="text_de",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="cookiesconsent",
            name="text_en",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="cookiesconsent",
            name="text_pl",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="cookiesconsent",
            name="text_ru",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="cookiesconsent",
            name="text_ua",
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
