# Generated by Django 4.1.7 on 2023-12-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0029_alter_cookiesconsent_analytics_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="image_alt_text",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="mission",
            name="image_alt_text_de",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="mission",
            name="image_alt_text_en",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="mission",
            name="image_alt_text_pl",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="mission",
            name="image_alt_text_ru",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="mission",
            name="image_alt_text_ua",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
