# Generated by Django 4.1.7 on 2023-10-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
