# Generated by Django 4.1.7 on 2023-10-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_blogpost_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
