# Generated by Django 5.0.1 on 2024-03-18 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_content_de_blogpost_content_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content_de',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='content_pl',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='content_ua',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title_pl',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title_ua',
        ),
    ]
